### ISSUE TITLE
Register heic/heif extensions

### ISSUE THREAD

**Issue by hpoul** [uploadcare/heif-image-plugin#14]
I have been migrating away from https://github.com/ciotto/pyheif-pillow-opener and got an error that `.heic` extension was not supported. After looking into it, it seems pillow-opener registered the extensions. I think it would be good to add it to this plugin as well:

https://github.com/ciotto/pyheif-pillow-opener/blob/5cf38718bcfb07edb9ac56e0a6dc13ff7b4e9830/pyheif_pillow_opener/__init__.py#L84-L88

```
Image.register_extensions(HeifImageFile.format, ['.heic', '.heif'])
```

**Comment by hpoul** [comment]
> Please provide some code example

It is used by the django ImageField validates to check if the filename has a valid file extension.. will provide an example later

**Comment by hpoul** [comment]
here is the django code which validates the file extension by simply using PIL's `Image.EXTENSION`

https://github.com/django/django/blob/21d8ea4eb3e22d458515b5278c8cd3a15b069799/django/core/validators.py#L570-L577

I guess this is not really a "bug" in heif-image-plugin, but a pain point when migrating from `pyheif-pillow-opener`.. If you don't want to add this maybe just add it to the readme. It's easy enough to just call `Image.register_extensions(HeifImageFile.format, ['.heic', '.heif'])` - but one has to know about that change.

**Comment by bigcat88** [comment]
do not forget about `.hif` extension ;)

**Comment by bigcat88** [comment]
For AVIF Pillow already has [extension](https://github.com/fdintino/pillow-avif-plugin) that registers it...
